# Generated by Django 2.0.2 on 2021-03-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepCycleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('struggling', models.IntegerField(null=True)),
                ('bedtime', models.IntegerField(null=True)),
                ('wakeuptime', models.IntegerField(null=True)),
                ('sleephours', models.IntegerField(null=True)),
            ],
        ),
    ]
