# Generated by Django 2.0.2 on 2021-03-16 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sleepapi', '0002_auto_20210316_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sleepcyclemodel',
            old_name='sleephours',
            new_name='sleepHours',
        ),
        migrations.AddField(
            model_name='sleepcyclemodel',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
